services:
  - type: web
    name: flight-tracker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn webapp:app
    envVars:
      - key: MONGODB_URI
        sync: false
